import { DarkTheme, DefaultTheme, type Theme } from "@react-navigation/native";

export const THEME = {
  light: {
    background: "#f8f8f8",
    tabBar: "#f8f8f8",
    foreground: "#1d293d",
    card: "#ffffff",
    cardForeground: "#1d293d",
    popover: "#ffffff",
    popoverForeground: "#1d293d",
    primary: "#6468f0",
    primaryForeground: "#ffffff",
    secondary: "#e4e8ef",
    secondaryForeground: "#364050",
    muted: "#f5f5f5",
    mutedForeground: "#6c727e",
    accent: "#e1e7fd",
    accentForeground: "#364050",
    destructive: "#f14444",
    destructiveForeground: "#ffffff",
    border: "#d0d4db",
    input: "#d0d4db",
    ring: "#6468f0",
    sidebar: "#f5f5f5",
    sidebarForeground: "#1d293d",
    sidebarPrimary: "#6468f0",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#e1e7fd",
    sidebarAccentForeground: "#364050",
    sidebarBorder: "#d0d4db",
    sidebarRing: "#6468f0",
    radius: "0.5rem",
    chart1: "#6468f0",
    chart2: "#4f46e5",
    chart3: "#443bc9",
    chart4: "#3730a5",
    chart5: "#312d84",
  },
  dark: {
    background: "#0f182b",
    tabBar: "#0f182b",
    foreground: "#e3e8ef",
    card: "#1d293d",
    cardForeground: "#e3e8ef",
    popover: "#1d293d",
    popoverForeground: "#e3e8ef",
    primary: "#818cf9",
    primaryForeground: "#0f182b",
    secondary: "#2f3848",
    secondaryForeground: "#d0d4db",
    muted: "#1d293d",
    mutedForeground: "#9ba2ae",
    accent: "#364050",
    accentForeground: "#d0d4db",
    destructive: "#f14444",
    destructiveForeground: "#ffffff",
    border: "#4b5666",
    input: "#4b5666",
    ring: "#818cf9",
    sidebar: "#1d293d",
    sidebarForeground: "#e3e8ef",
    sidebarPrimary: "#818cf9",
    sidebarPrimaryForeground: "#0f182b",
    sidebarAccent: "#364050",
    sidebarAccentForeground: "#d0d4db",
    sidebarBorder: "#4b5666",
    sidebarRing: "#818cf9",
    radius: "0.5rem",
    chart1: "#818cf9",
    chart2: "#6468f0",
    chart3: "#4f46e5",
    chart4: "#443bc9",
    chart5: "#3730a5",
  },
};

export const NAV_THEME: Record<"light" | "dark", Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
